// src/routes/receipts.js
// ============================================================================
// Public receipt endpoints (no auth required — customer-facing)
//
// GET /verify/:orderId  — Render an HTML itemised receipt with QR code
//                         Falls back to building from orders table if no
//                         invoice row exists yet (race window).
//
// GET /r/:token         — Redirect token → 1-hour signed Supabase Storage URL
//                         For PNG receipts generated by the Python service.
// ============================================================================

'use strict';

const express = require('express');
const router  = express.Router();

const { supabaseAdmin } = require('../config/supabase');
const { buildInvoicePayload, GST_RATES } = require('./invoices');

function escHtml(str) {
  return String(str ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// ── GET /verify/:orderId ──────────────────────────────────────────────────────

router.get('/verify/:orderId', async (req, res) => {
  try {
    const { orderId } = req.params;
    if (!orderId) return res.status(400).send('<p>Order ID required</p>');

    // Step 1: Try invoice table first (fastest, already structured)
    const { data: invoice } = await supabaseAdmin
      .from('invoices').select('payload, grand_total, generated_at')
      .eq('order_id', orderId).maybeSingle();

    let p = invoice?.payload ?? null;

    // Step 2: Build from orders table (handles race window before invoice persists)
    if (!p) {
      const { data: order } = await supabaseAdmin
        .from('orders')
        .select('*, order_items(quantity, unit_price, menu_item:menu_item_id(name, category))')
        .eq('id', orderId).single();

      if (!order) {
        return res.status(404).send(`<!DOCTYPE html><html><head>
          <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
          <title>Receipt not found</title></head>
          <body style="font-family:sans-serif;text-align:center;padding:48px 24px;color:#888">
            <p style="font-size:44px;margin-bottom:12px">🔍</p>
            <p style="font-size:16px;color:#555;margin-bottom:8px">Receipt not found</p>
            <p style="font-size:12px">Order: ${escHtml(orderId)}</p>
          </body></html>`);
      }

      const { data: restaurant } = await supabaseAdmin
        .from('restaurants').select('id, name, gstin, brand_id')
        .eq('id', order.restaurant_id).maybeSingle();

      p = buildInvoicePayload(order, restaurant ?? {}, GST_RATES.default);
    }

    // Step 3: Render HTML receipt
    const receiptUrl = `${process.env.API_BASE_URL ?? 'https://api.autom8.works'}/verify/${orderId}`;
    const im         = p.invoice_meta        ?? {};
    const fb         = p.financial_breakdown ?? {};
    const lineItems  = p.line_items          ?? [];

    const itemRows = lineItems.map(li => `
      <tr>
        <td class="item-name">${escHtml(li.name)}${(li.quantity ?? 1) > 1 ? ` <span class="item-qty-inline">×${li.quantity}</span>` : ''}</td>
        <td class="item-price">₹${(li.line_total ?? 0).toFixed(2)}</td>
      </tr>`
    ).join('');

    const deliveryRow = (fb.packaging_or_delivery_charge ?? 0) > 0
      ? `<div class="total-row"><span>Delivery charge</span><span>₹${fb.packaging_or_delivery_charge.toFixed(2)}</span></div>`
      : '';

    const dateStr = new Date(im.invoice_date ?? Date.now()).toLocaleString('en-IN', {
      day: '2-digit', month: 'short', year: 'numeric',
      hour: '2-digit', minute: '2-digit', hour12: true, timeZone: 'Asia/Kolkata',
    });

    const fulfillmentLabel = (im.fulfillment_type ?? 'dine_in')
      .replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <meta name="theme-color" content="#1a1a1a" />
  <title>Receipt — ${escHtml(im.order_number ?? orderId.slice(-8))}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f0f0ee; min-height: 100vh; padding: 20px 16px 48px; display: flex; align-items: flex-start; justify-content: center; }
    .receipt { background: #fff; border-radius: 16px; width: 100%; max-width: 400px; box-shadow: 0 2px 24px rgba(0,0,0,.1); overflow: hidden; }
    .rh { background: #1a1a1a; color: #fff; padding: 22px 20px 18px; text-align: center; }
    .rh-name  { font-size: 17px; font-weight: 600; letter-spacing: .02em; }
    .rh-order { font-size: 12px; color: #888; margin-top: 3px; }
    .rh-badge { display: inline-block; margin-top: 10px; padding: 3px 12px; border-radius: 20px; font-size: 11px; font-weight: 600; letter-spacing: .04em; background: rgba(34,197,94,.15); color: #22c55e; border: 1px solid rgba(34,197,94,.3); }
    .rb { padding: 18px 20px 20px; }
    .meta { display: flex; justify-content: space-between; font-size: 12px; margin-bottom: 6px; }
    .meta .lbl { color: #aaa; }
    .meta .val { color: #333; font-weight: 500; }
    .dv { border: none; border-top: 1px dashed #e0e0dc; margin: 14px 0; }
    .items { width: 100%; border-collapse: collapse; }
    .items td { padding: 7px 0; vertical-align: top; }
    .item-name { font-size: 13px; color: #222; padding-right: 10px; }
    .item-qty-inline { font-size: 11px; color: #aaa; }
    .item-price { font-size: 13px; color: #222; text-align: right; white-space: nowrap; font-variant-numeric: tabular-nums; }
    .totals { margin-top: 4px; }
    .total-row { display: flex; justify-content: space-between; font-size: 12px; color: #888; margin-bottom: 6px; }
    .total-row.grand { font-size: 15px; font-weight: 600; color: #111; padding-top: 9px; margin-top: 3px; border-top: 1px solid #e0e0dc; }
    .pay-note { margin-top: 14px; padding: 10px 14px; background: #f0f9f4; border-radius: 8px; font-size: 12px; color: #15803d; text-align: center; font-weight: 500; }
    .qr-section { margin-top: 18px; padding-top: 16px; border-top: 1px dashed #e0e0dc; text-align: center; }
    .qr-label { font-size: 10px; color: #bbb; letter-spacing: .04em; text-transform: uppercase; margin-bottom: 10px; }
    #qrcode { display: inline-block; }
    #qrcode canvas, #qrcode img { border-radius: 6px; }
    .rfooter { text-align: center; font-size: 10px; color: #ccc; margin-top: 12px; padding-bottom: 2px; }
    .print-btn { display: block; width: 100%; margin-top: 16px; padding: 13px; background: #1a1a1a; color: #fff; border: none; border-radius: 10px; font-size: 13px; font-weight: 500; cursor: pointer; letter-spacing: .03em; }
    .print-btn:active { opacity: .85; }
    @media print { body { background: #fff; padding: 0; } .receipt { box-shadow: none; border-radius: 0; max-width: 100%; } .print-btn { display: none; } }
  </style>
</head>
<body>
  <div class="receipt">
    <div class="rh">
      <div class="rh-name">${escHtml(im.store_name || 'Restaurant')}</div>
      <div class="rh-order">Order #${escHtml(im.order_number ?? orderId.slice(-8))}</div>
      <div class="rh-badge">✓ Order Received</div>
    </div>
    <div class="rb">
      <div class="meta"><span class="lbl">Date &amp; time</span><span class="val">${escHtml(dateStr)}</span></div>
      <div class="meta"><span class="lbl">Order type</span><span class="val">${escHtml(fulfillmentLabel)}</span></div>
      ${im.gstin ? `<div class="meta"><span class="lbl">GSTIN</span><span class="val">${escHtml(im.gstin)}</span></div>` : ''}
      <hr class="dv" />
      <table class="items"><tbody>${itemRows}</tbody></table>
      <hr class="dv" />
      <div class="totals">
        <div class="total-row"><span>Subtotal</span><span>₹${(fb.subtotal_base_price ?? 0).toFixed(2)}</span></div>
        <div class="total-row"><span>GST (CGST ${fb.cgst_rate_pct ?? 2.5}% + SGST ${fb.sgst_rate_pct ?? 2.5}%)</span><span>₹${(fb.total_gst ?? 0).toFixed(2)}</span></div>
        ${deliveryRow}
        <div class="total-row grand"><span>Total</span><span>₹${(fb.grand_total ?? 0).toFixed(2)}</span></div>
      </div>
      <div class="pay-note">💚 Payment can be made at the counter</div>
      <div class="qr-section">
        <div class="qr-label">Scan to open this receipt</div>
        <div id="qrcode"></div>
        <div class="rfooter">Powered by Autom8 · ${escHtml(im.store_name || '')}</div>
      </div>
      <button class="print-btn" onclick="window.print()">🖨 Save / Print receipt</button>
    </div>
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"
          integrity="sha512-CNgIRecGo7nphbeZ04Sc13ka07paqdeTu0WR1IM4kNcpmBAUSHSi2jPyei5Z0DxUi0GsfcOQhHFAP7uYBiWzA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script>
    try {
      new QRCode(document.getElementById('qrcode'), {
        text: ${JSON.stringify(receiptUrl)},
        width: 128, height: 128,
        colorDark: '#1a1a1a', colorLight: '#ffffff',
        correctLevel: QRCode.CorrectLevel.M,
      });
    } catch(e) {
      document.getElementById('qrcode').innerHTML = '<p style="font-size:11px;color:#bbb;padding:10px">QR unavailable</p>';
    }
  </script>
</body>
</html>`;

    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    res.setHeader('Cache-Control', 'no-store');
    res.send(html);

  } catch (err) {
    console.error('[verify-receipt]', err.message);
    res.status(500).send(`<!DOCTYPE html><html><head>
      <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
      <title>Error</title></head>
      <body style="font-family:sans-serif;text-align:center;padding:48px 24px;color:#888">
        <p style="font-size:44px;margin-bottom:12px">⚠️</p>
        <p>Could not load receipt. Please try again.</p>
      </body></html>`);
  }
});

// ── GET /r/:token — Supabase Storage PNG receipt redirect ─────────────────────

router.get('/r/:token', async (req, res) => {
  const token  = req.params.token;
  const sbBase = (process.env.AUTOM8_SUPABASE_URL || '').replace(/\/$/, '');
  const sbKey  = process.env.AUTOM8_SUPABASE_SERVICE_KEY || '';

  if (!sbBase || !sbKey) return res.status(503).send('<h1>Service unavailable</h1>');

  try {
    // List bucket files and find one matching this token
    const listResp = await fetch(`${sbBase}/storage/v1/object/list/Receipts`, {
      method:  'POST',
      headers: { 'apikey': sbKey, 'Authorization': `Bearer ${sbKey}`, 'Content-Type': 'application/json' },
      body:    JSON.stringify({ prefix: '', limit: 200 }),
    });
    const files = await listResp.json();
    const match = Array.isArray(files) ? files.find(f => f.name?.includes(token)) : null;

    if (!match) {
      return res.status(404).send(`<html><body style="font-family:sans-serif;padding:40px">
        <h2>Receipt not found or expired</h2>
        <p>Receipts are available for 48 hours after your order.</p>
        </body></html>`);
    }

    // Generate a fresh 1-hour signed URL
    const signResp = await fetch(`${sbBase}/storage/v1/object/sign/Receipts/${match.name}`, {
      method:  'POST',
      headers: { 'apikey': sbKey, 'Authorization': `Bearer ${sbKey}`, 'Content-Type': 'application/json' },
      body:    JSON.stringify({ expiresIn: 3600 }),
    });
    const signData   = await signResp.json();
    const signedPath = signData.signedURL || '';

    if (!signedPath) return res.status(503).send('<h1>Could not generate receipt link</h1>');

    return res.redirect(`${sbBase}/storage/v1${signedPath}`);
  } catch (err) {
    console.error('[receipt-redirect] Error:', err.message);
    return res.status(500).send('<h1>Error retrieving receipt</h1>');
  }
});

module.exports = router;
